[package]
name = "rust-overlaps"
version = "1.1"
authors = ["sirkibsirkib <christopher.esterhuyse@gmail.com>"]

[dependencies]
bio = "0.13.0"
rand = "0.3"
clap = "2.24.1"
bidir-map = "0.3.2"
csv = "0.15.0"
cue = "0.1.0"
num_cpus = "1.4.0"
stacker = "0.1.2"
